import { Feather } from '@expo/vector-icons';
import * as Haptics from 'expo-haptics';
import React from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useColors } from '@/hooks/useColors';
import { useDailyBalance } from '@/context/DailyBalanceContext';
import { getDayNames, useCopy } from '@/lib/i18n';
import { getWeeklyPlan } from '@/lib/weeklyPlan';

export default function PlanScreen() {
  const colors = useColors();
  const insets = useSafeAreaInsets();
  const { state, setMode, setSelectedDay, getLog, toggleMeal, toggleExercise, toggleSchedule, todayDay } = useDailyBalance();
  const t = useCopy(state.language);
  const dayNames = getDayNames(state.language);
  const plan = getWeeklyPlan(state.language, state.selectedDay);
  const log = getLog(state.selectedDay, state.mode);
  const schedule = state.mode === 'work' ? plan.workSchedule : plan.vacationSchedule;
  const completed = plan.meals.filter((item) => log.meals[item.id]).length + plan.exercises.filter((item) => log.exercises[item.id]).length + schedule.filter((item) => log.schedule[item.id]).length;
  const total = plan.meals.length + plan.exercises.length + schedule.length;
  const mealLabels: Record<string, string> = { breakfast: t.breakfast, morningSnack: t.morningSnack, lunch: t.lunch, afternoonSnack: t.afternoonSnack, dinner: t.dinner };

  return (
    <View style={[styles.screen, { backgroundColor: colors.background, paddingTop: insets.top, direction: state.language === 'ar' ? 'rtl' : 'ltr' }]}>
      <ScrollView contentContainerStyle={[styles.content, { paddingBottom: insets.bottom + 98 }]} showsVerticalScrollIndicator={false}>
        <Text style={[styles.kicker, { color: colors.primary }]}>{t.plan}</Text>
        <View style={styles.titleRow}><View><Text style={[styles.title, { color: colors.navy }]}>{t.week}</Text><Text style={[styles.subtitle, { color: colors.mutedForeground }]}>{completed}/{total} {t.completed} · {dayNames[state.selectedDay]}</Text></View><View style={[styles.weekIcon, { backgroundColor: colors.mint }]}><Feather name="calendar" size={20} color={colors.primary} /></View></View>
        <Text style={[styles.chooseDay, { color: colors.mutedForeground }]}>{t.chooseDay}</Text>
        <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.dayRow}>
          {dayNames.map((day, index) => <Pressable key={day} testID={`day-${index}`} onPress={() => { Haptics.selectionAsync(); setSelectedDay(index); }} style={[styles.dayChip, { backgroundColor: state.selectedDay === index ? colors.primary : colors.card }, index === todayDay && state.selectedDay !== index && { borderColor: colors.primary, borderWidth: 1 }]}><Text style={[styles.dayName, { color: state.selectedDay === index ? colors.card : colors.navy }]}>{day}</Text><Text style={[styles.dayNumber, { color: state.selectedDay === index ? colors.mint : colors.mutedForeground }]}>{index === todayDay ? t.today : `${index + 1}/7`}</Text></Pressable>)}
        </ScrollView>

        <View style={[styles.modeTabs, { backgroundColor: colors.mint }]}><Pressable testID="mode-work" onPress={() => { Haptics.selectionAsync(); setMode('work'); }} style={[styles.modeTab, state.mode === 'work' && { backgroundColor: colors.card }]}><Feather name="briefcase" size={15} color={state.mode === 'work' ? colors.primary : colors.mutedForeground} /><Text style={[styles.modeTabText, { color: state.mode === 'work' ? colors.navy : colors.mutedForeground }]}>{t.work}</Text></Pressable><Pressable testID="mode-vacation" onPress={() => { Haptics.selectionAsync(); setMode('vacation'); }} style={[styles.modeTab, state.mode === 'vacation' && { backgroundColor: colors.card }]}><Feather name="sun" size={15} color={state.mode === 'vacation' ? colors.primary : colors.mutedForeground} /><Text style={[styles.modeTabText, { color: state.mode === 'vacation' ? colors.navy : colors.mutedForeground }]}>{t.vacation}</Text></Pressable></View>

        <View style={styles.heading}><Text style={[styles.sectionTitle, { color: colors.navy }]}>{t.meals}</Text><Text style={[styles.count, { color: colors.mutedForeground }]}>{plan.meals.filter((item) => log.meals[item.id]).length}/5</Text></View>
        <View style={[styles.mealCard, { backgroundColor: colors.card }]}>{plan.meals.map((meal, index) => <Pressable key={meal.id} testID={`plan-meal-${meal.id}`} onPress={() => { Haptics.selectionAsync(); toggleMeal(meal.id, state.selectedDay, state.mode); }} style={({ pressed }) => [styles.mealRow, index > 0 && { borderTopWidth: 1, borderTopColor: colors.border }, pressed && { opacity: 0.7 }]}><View style={[styles.check, { backgroundColor: log.meals[meal.id] ? colors.primary : colors.background, borderColor: log.meals[meal.id] ? colors.primary : colors.border }]}>{log.meals[meal.id] && <Feather name="check" size={13} color={colors.card} />}</View><View style={styles.mealCopy}><Text style={[styles.mealSlot, { color: colors.primary }]}>{mealLabels[meal.slot]}</Text><Text style={[styles.mealTitle, { color: colors.navy }, log.meals[meal.id] && styles.done]}>{meal.title}</Text><Text style={[styles.mealDetail, { color: colors.mutedForeground }]}>{meal.detail}</Text></View><Text style={[styles.time, { color: colors.mutedForeground }]}>{meal.time}</Text></Pressable>)}</View>

        <View style={styles.heading}><Text style={[styles.sectionTitle, { color: colors.navy }]}>{t.todayExercise}</Text><Text style={[styles.count, { color: colors.mutedForeground }]}>{plan.exercises.length} {t.movement.toLowerCase()}</Text></View>
        {plan.exercises.map((exercise) => <Pressable key={exercise.id} testID={`plan-exercise-${exercise.id}`} onPress={() => { Haptics.selectionAsync(); toggleExercise(exercise.id, state.selectedDay, state.mode); }} style={({ pressed }) => [styles.exerciseCard, { backgroundColor: log.exercises[exercise.id] ? colors.mint : colors.card }, pressed && { opacity: 0.72 }]}><View style={[styles.exerciseIcon, { backgroundColor: log.exercises[exercise.id] ? colors.card : colors.lavender }]}><Feather name="activity" size={18} color={log.exercises[exercise.id] ? colors.primary : colors.lavenderStrong} /></View><View style={styles.exerciseCopy}><Text style={[styles.exerciseTitle, { color: colors.navy }, log.exercises[exercise.id] && styles.done]}>{exercise.title}</Text><Text style={[styles.exerciseMeta, { color: colors.mutedForeground }]}>{exercise.duration} · {exercise.difficulty}</Text><Text style={[styles.exerciseInstruction, { color: colors.mutedForeground }]}>{t.instructions}: {exercise.instructions}</Text><Text style={[styles.exerciseInstruction, { color: colors.mutedForeground }]}>{t.rest}: {exercise.rest}</Text></View><View style={[styles.exerciseAction, { backgroundColor: log.exercises[exercise.id] ? colors.primary : colors.background }]}>{log.exercises[exercise.id] ? <Feather name="check" size={15} color={colors.card} /> : <Feather name="play" size={15} color={colors.primary} />}</View></Pressable>)}

        <View style={styles.heading}><Text style={[styles.sectionTitle, { color: colors.navy }]}>{t.schedule}</Text><Text style={[styles.count, { color: colors.mutedForeground }]}>{schedule.length} {t.tasks}</Text></View>
        <View style={[styles.scheduleCard, { backgroundColor: colors.card }]}>{schedule.map((item, index) => <Pressable key={item.id} testID={`plan-schedule-${item.id}`} onPress={() => { Haptics.selectionAsync(); toggleSchedule(item.id, state.selectedDay, state.mode); }} style={({ pressed }) => [styles.scheduleRow, index > 0 && { borderTopWidth: 1, borderTopColor: colors.border }, pressed && { opacity: 0.7 }]}><View style={[styles.scheduleDot, { backgroundColor: log.schedule[item.id] ? colors.primary : item.kind === 'meal' ? colors.coral : item.kind === 'movement' ? colors.lavenderStrong : item.kind === 'work' ? colors.primary : colors.amber }]} /><Text style={[styles.scheduleTime, { color: colors.navy }]}>{item.time}</Text><Text style={[styles.scheduleTitle, { color: colors.navy }, log.schedule[item.id] && styles.done]}>{item.title}</Text><View style={[styles.check, { backgroundColor: log.schedule[item.id] ? colors.primary : colors.background, borderColor: log.schedule[item.id] ? colors.primary : colors.border }]}>{log.schedule[item.id] && <Feather name="check" size={13} color={colors.card} />}</View></Pressable>)}</View>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  screen: { flex: 1 }, content: { paddingHorizontal: 20, paddingTop: 26 }, kicker: { fontSize: 11, textTransform: 'uppercase', letterSpacing: 1.2, fontWeight: '800', marginBottom: 7 }, titleRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 5 }, title: { fontSize: 30, fontWeight: '700', letterSpacing: -0.7 }, subtitle: { fontSize: 12, marginTop: 5 }, weekIcon: { width: 47, height: 47, borderRadius: 16, alignItems: 'center', justifyContent: 'center' }, chooseDay: { fontSize: 11, fontWeight: '700', marginTop: 19, marginBottom: 9 }, dayRow: { gap: 8, paddingBottom: 20 }, dayChip: { width: 78, minHeight: 60, borderRadius: 16, padding: 9, justifyContent: 'space-between' }, dayName: { fontSize: 11, fontWeight: '700' }, dayNumber: { fontSize: 9, fontWeight: '600' }, modeTabs: { borderRadius: 17, padding: 4, flexDirection: 'row', gap: 4, marginBottom: 26 }, modeTab: { flex: 1, minHeight: 43, borderRadius: 13, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7 }, modeTabText: { fontSize: 12, fontWeight: '700' }, heading: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'baseline', marginBottom: 11, marginTop: 2 }, sectionTitle: { fontSize: 18, fontWeight: '700', letterSpacing: -0.3 }, count: { fontSize: 11, fontWeight: '600' }, mealCard: { borderRadius: 21, paddingHorizontal: 14, marginBottom: 24 }, mealRow: { minHeight: 79, flexDirection: 'row', alignItems: 'center', gap: 10 }, check: { width: 25, height: 25, borderRadius: 8, borderWidth: 1, alignItems: 'center', justifyContent: 'center' }, mealCopy: { flex: 1 }, mealSlot: { fontSize: 10, fontWeight: '800', marginBottom: 3 }, mealTitle: { fontSize: 13, fontWeight: '700', marginBottom: 3 }, mealDetail: { fontSize: 10, lineHeight: 15 }, time: { fontSize: 11, fontWeight: '700' }, done: { opacity: 0.5, textDecorationLine: 'line-through' }, exerciseCard: { minHeight: 115, borderRadius: 19, padding: 12, flexDirection: 'row', alignItems: 'flex-start', gap: 11, marginBottom: 10 }, exerciseIcon: { width: 42, height: 42, borderRadius: 14, alignItems: 'center', justifyContent: 'center' }, exerciseCopy: { flex: 1 }, exerciseTitle: { fontSize: 14, fontWeight: '700', marginBottom: 4 }, exerciseMeta: { fontSize: 11, marginBottom: 6 }, exerciseInstruction: { fontSize: 10, lineHeight: 15, marginBottom: 3 }, exerciseAction: { width: 32, height: 32, borderRadius: 11, alignItems: 'center', justifyContent: 'center' }, scheduleCard: { borderRadius: 21, paddingHorizontal: 14 }, scheduleRow: { minHeight: 53, flexDirection: 'row', alignItems: 'center', gap: 9 }, scheduleDot: { width: 8, height: 8, borderRadius: 4 }, scheduleTime: { width: 43, fontSize: 11, fontWeight: '700' }, scheduleTitle: { flex: 1, fontSize: 12, fontWeight: '600' },
});