import { Feather } from '@expo/vector-icons';
import * as Haptics from 'expo-haptics';
import React, { useState } from 'react';
import { Alert, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useColors } from '@/hooks/useColors';
import { Language, useDailyBalance } from '@/context/DailyBalanceContext';
import { getReminderLabel, useCopy } from '@/lib/i18n';

export default function SettingsScreen() {
  const colors = useColors();
  const insets = useSafeAreaInsets();
  const { state, reminders, setLanguage, updateProfile, toggleReminder, resetToday } = useDailyBalance();
  const t = useCopy(state.language);
  const [modal, setModal] = useState(false);
  const [name, setName] = useState(state.profileName);
  const [current, setCurrent] = useState(String(state.currentWeight));
  const [target, setTarget] = useState(String(state.targetWeight));
  const languageLabels: Record<Language, Record<Language, string>> = {
    en: { en: 'English', fr: 'French', ar: 'Arabic' },
    fr: { en: 'Anglais', fr: 'Français', ar: 'Arabe' },
    ar: { en: 'الإنجليزية', fr: 'الفرنسية', ar: 'العربية' },
  };
  const languages: { key: Language; short: string }[] = [{ key: 'en', short: 'EN' }, { key: 'fr', short: 'FR' }, { key: 'ar', short: 'ع' }];
  return (
    <View style={[styles.screen, { backgroundColor: colors.background, paddingTop: insets.top, direction: state.language === 'ar' ? 'rtl' : 'ltr' }]}>
      <ScrollView contentContainerStyle={[styles.content, { paddingBottom: insets.bottom + 98 }]} showsVerticalScrollIndicator={false}>
        <Text style={[styles.kicker, { color: colors.primary }]}>{t.settings}</Text>
        <Text style={[styles.title, { color: colors.navy }]}>{t.profile}</Text>
        <Pressable testID="edit-profile" onPress={() => setModal(true)} style={({ pressed }) => [styles.profileCard, { backgroundColor: colors.card }, pressed && { opacity: 0.72 }]}><View style={[styles.avatar, { backgroundColor: colors.coral }]}><Text style={[styles.avatarText, { color: colors.navy }]}>{state.profileName.slice(0, 1).toUpperCase()}</Text></View><View style={styles.profileCopy}><Text style={[styles.profileName, { color: colors.navy }]}>{state.profileName}</Text><Text style={[styles.profileMeta, { color: colors.mutedForeground }]}>{state.currentWeight.toFixed(1)} {t.kg} → {state.targetWeight.toFixed(1)} {t.kg}</Text></View><Feather name="edit-3" size={17} color={colors.mutedForeground} /></Pressable>
        <Text style={[styles.label, { color: colors.mutedForeground }]}>{t.language}</Text>
        <View style={[styles.languageRow, { backgroundColor: colors.card }]}>{languages.map((language) => <Pressable key={language.key} testID={`language-${language.key}`} onPress={() => { Haptics.selectionAsync(); setLanguage(language.key); }} style={[styles.languageOption, state.language === language.key && { backgroundColor: colors.mint }]}><Text style={[styles.languageShort, { color: state.language === language.key ? colors.primary : colors.mutedForeground }]}>{language.short}</Text><Text style={[styles.languageLabel, { color: colors.navy }]}>{languageLabels[state.language][language.key]}</Text>{state.language === language.key && <Feather name="check" size={14} color={colors.primary} />}</Pressable>)}</View>
        <View style={styles.heading}><Text style={[styles.sectionTitle, { color: colors.navy }]}>{t.notifications}</Text><Text style={[styles.count, { color: colors.mutedForeground }]}>{state.mode === 'work' ? t.work : t.vacation}</Text></View>
        <View style={[styles.reminders, { backgroundColor: colors.card }]}>{reminders.map((reminder, index) => <View key={reminder.id} style={[styles.reminderRow, index > 0 && { borderTopWidth: 1, borderTopColor: colors.border }]}><View style={[styles.reminderIcon, { backgroundColor: reminder.id === 'weight' ? colors.lavender : colors.mint }]}><Feather name={reminder.id === 'water' ? 'droplet' : reminder.id === 'weight' ? 'activity' : 'clock'} size={15} color={reminder.id === 'weight' ? colors.lavenderStrong : colors.primary} /></View><View style={styles.reminderCopy}><Text style={[styles.reminderLabel, { color: colors.navy }]}>{getReminderLabel(state.language, reminder.id)}</Text><Text style={[styles.reminderTime, { color: colors.mutedForeground }]}>{reminder.time} · {reminder.enabled ? t.enabled : t.disabled}</Text></View><Pressable testID={`reminder-${reminder.id}`} accessibilityLabel={getReminderLabel(state.language, reminder.id)} onPress={async () => { const enabled = await toggleReminder(reminder.id); if (!enabled && !reminder.enabled) Alert.alert(t.notifications, t.notificationsDenied); }} style={[styles.switch, { backgroundColor: reminder.enabled ? colors.primary : colors.muted }]}><View style={[styles.switchThumb, reminder.enabled && { transform: [{ translateX: 17 }] }]} /></Pressable></View>)}</View>
        <Pressable testID="reset-today" onPress={() => { Alert.alert(t.reset, t.resetNote, [{ text: t.cancel, style: 'cancel' }, { text: t.reset, style: 'destructive', onPress: resetToday }]); }} style={({ pressed }) => [styles.resetButton, { borderColor: colors.border }, pressed && { opacity: 0.7 }]}><Feather name="refresh-cw" size={15} color={colors.destructive} /><Text style={[styles.resetText, { color: colors.destructive }]}>{t.reset}</Text></Pressable>
        <Text style={[styles.saved, { color: colors.mutedForeground }]}><Feather name="lock" size={11} color={colors.mutedForeground} />  {t.saved}</Text>
      </ScrollView>
      <Modal visible={modal} transparent animationType="slide" onRequestClose={() => setModal(false)}><View style={styles.modalBackdrop}><View style={[styles.modal, { backgroundColor: colors.card, paddingBottom: insets.bottom + 18 }]}><View style={styles.modalHandle} /><Text style={[styles.modalTitle, { color: colors.navy }]}>{t.profile}</Text><TextInput value={name} onChangeText={setName} placeholder={t.name} placeholderTextColor={colors.mutedForeground} style={[styles.input, { backgroundColor: colors.background, borderColor: colors.border, color: colors.navy }]} /><View style={styles.inputRow}><TextInput value={current} onChangeText={setCurrent} keyboardType="decimal-pad" placeholder={t.current} placeholderTextColor={colors.mutedForeground} style={[styles.input, styles.halfInput, { backgroundColor: colors.background, borderColor: colors.border, color: colors.navy }]} /><TextInput value={target} onChangeText={setTarget} keyboardType="decimal-pad" placeholder={t.target} placeholderTextColor={colors.mutedForeground} style={[styles.input, styles.halfInput, { backgroundColor: colors.background, borderColor: colors.border, color: colors.navy }]} /></View><Pressable testID="save-profile" onPress={() => { const c = Number(current.replace(',', '.')); const tar = Number(target.replace(',', '.')); if (Number.isFinite(c) && Number.isFinite(tar) && c > 0 && tar > 0) { updateProfile(name, c, tar); setModal(false); } }} style={[styles.save, { backgroundColor: colors.primary }]}><Text style={[styles.saveText, { color: colors.card }]}>{t.save}</Text></Pressable><Pressable onPress={() => setModal(false)} style={styles.cancel}><Text style={[styles.cancelText, { color: colors.mutedForeground }]}>{t.done}</Text></Pressable></View></View></Modal>
    </View>
  );
}

const styles = StyleSheet.create({
  screen: { flex: 1 }, content: { paddingHorizontal: 20, paddingTop: 26 }, kicker: { fontSize: 11, textTransform: 'uppercase', letterSpacing: 1.2, fontWeight: '800', marginBottom: 7 }, title: { fontSize: 30, fontWeight: '700', letterSpacing: -0.7, marginBottom: 20 }, profileCard: { borderRadius: 21, padding: 15, flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 25 }, avatar: { width: 46, height: 46, borderRadius: 17, alignItems: 'center', justifyContent: 'center' }, avatarText: { fontSize: 19, fontWeight: '800' }, profileCopy: { flex: 1 }, profileName: { fontSize: 15, fontWeight: '700', marginBottom: 4 }, profileMeta: { fontSize: 11 }, label: { fontSize: 11, fontWeight: '700', marginBottom: 9, textTransform: 'uppercase', letterSpacing: 0.8 }, languageRow: { borderRadius: 20, padding: 7, marginBottom: 28 }, languageOption: { minHeight: 46, borderRadius: 14, paddingHorizontal: 10, flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 2 }, languageShort: { width: 28, fontSize: 11, fontWeight: '800' }, languageLabel: { flex: 1, fontSize: 13, fontWeight: '600' }, heading: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'baseline', marginBottom: 11 }, sectionTitle: { fontSize: 18, fontWeight: '700' }, count: { fontSize: 11 }, reminders: { borderRadius: 21, paddingHorizontal: 14, marginBottom: 21 }, reminderRow: { minHeight: 72, flexDirection: 'row', alignItems: 'center', gap: 11 }, reminderIcon: { width: 34, height: 34, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, reminderCopy: { flex: 1 }, reminderLabel: { fontSize: 13, fontWeight: '700', marginBottom: 4 }, reminderTime: { fontSize: 11 }, switch: { width: 42, height: 25, borderRadius: 13, padding: 3, justifyContent: 'center' }, switchThumb: { width: 19, height: 19, borderRadius: 10, backgroundColor: '#FFFFFF' }, resetButton: { height: 46, borderWidth: 1, borderRadius: 15, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7 }, resetText: { fontSize: 12, fontWeight: '700' }, saved: { fontSize: 11, textAlign: 'center', marginTop: 18 }, modalBackdrop: { flex: 1, backgroundColor: 'rgba(23,52,59,0.4)', justifyContent: 'flex-end' }, modal: { borderTopLeftRadius: 28, borderTopRightRadius: 28, padding: 22 }, modalHandle: { width: 36, height: 4, borderRadius: 3, backgroundColor: '#DCE8E2', alignSelf: 'center', marginBottom: 22 }, modalTitle: { fontSize: 23, fontWeight: '700', marginBottom: 17 }, input: { height: 51, borderWidth: 1, borderRadius: 16, paddingHorizontal: 15, fontSize: 15, marginBottom: 12 }, inputRow: { flexDirection: 'row', gap: 10 }, halfInput: { flex: 1 }, save: { height: 50, borderRadius: 16, alignItems: 'center', justifyContent: 'center', marginTop: 1 }, saveText: { fontSize: 14, fontWeight: '700' }, cancel: { height: 43, alignItems: 'center', justifyContent: 'center' }, cancelText: { fontSize: 13, fontWeight: '600' },
});